#!/usr/bin/env bash

# remove everything
[[ -a $HOME/.hammerspoon ]] && rm $HOME/.hammerspoon
[[ -a $HOME/.zsh ]] && rm $HOME/.zsh
[[ -a $HOME/.zshrc ]] && rm $HOME/.zshrc
[[ -a $HOME/.vim ]] && rm $HOME/.vim
[[ -a $HOME/.vimrc ]] && rm $HOME/.vimrc
[[ -a $HOME/.gvimrc ]] && rm $HOME/.gvimrc

# hammerspoon
ln -s $PWD/hammerspoon $HOME/.hammerspoon

# zsh
ln -s $PWD/zsh $HOME/.zsh
ln -s $PWD/zsh/zshrc $HOME/.zshrc

# vim
ln -s $PWD/vim $HOME/.vim
ln -s $PWD/vim/vimrc $HOME/.vimrc
ln -s $PWD/vim/gvimrc $HOME/.gvimrc

