#!/usr/bin/env bash

# remove everything
rm $HOME/.hammerspoon
rm $HOME/.zsh
rm $HOME/.zshrc
rm $HOME/.vim
rm $HOME/.vimrc
rm $HOME/.gvimrc

# hammerspoon
ln -s $PWD/hammerspoon $HOME/.hammerspoon

# zsh
ln -s $PWD/zsh $HOME/.zsh
ln -s $PWD/zsh/zshrc $HOME/.zshrc

# vim
ln -s $PWD/vim $HOME/.vim
ln -s $PWD/vim/vimrc $HOME/.vimrc
ln -s $PWD/vim/gvimrc $HOME/.gvimrc

