" formatting stuff
set number
set nowrap
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set autochdir
set clipboard=unnamed
set backspace=2

" colors
syntax on
colorscheme molokai
set cursorline
highlight clear LineNr

" remappings
let mapleader = "\<Space>"
noremap e w
noremap q b

noremap d l
noremap w gk
noremap s gj
noremap a h

noremap j h
noremap k j
noremap l k
noremap ; l

" clear collisions from wasd-ing
noremap r d
noremap rr dd

" default :w
noremap <Leader>w :w<CR>
noremap <Leader>q :wq<CR>

"yell at you if you use arrow keys in normal mode
nnoremap <Up> :echo "Press w."<CR>
nnoremap <Down> :echo "Press s."<CR>
nnoremap <Left> :echo "Press a."<CR>
nnoremap <Right> :echo "Press d."<CR>

" limelight
au VimEnter * Limelight 0.6

" rainbow parens!
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" python formatting
au BufRead,BufNewFile *.py,*.pyw set tabstop=4
au BufRead,BufNewFile *.py,*.pyw set softtabstop=4
au BufRead,BufNewFile *.py,*.pyw set shiftwidth=4

" markdown
au BufRead,BufNewFile *.md,*.markdown,*.txt set wrap linebreak nolist

