"rformatting stuff
set number
set nowrap
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set autochdir
au BufNewFile *.* set fileformat=unix
set clipboard=unnamed

" colors
syntax on
colorscheme dracula
let g:airline_theme='dracula'

" remappings
let mapleader = "\<Space>"
noremap e w
noremap q b

noremap d l
noremap w k
noremap s j
noremap a h

noremap j h
noremap k j
noremap l k
noremap ; l

" clear collisions from wasd-ing
nnoremap f i
noremap r d
noremap rr dd

" default :w
noremap <Leader>w :w<CR>
noremap <Leader>q :wq<CR>

noremap jj :q<CR>
"yell at you if you use arrow keys in normal mode
nnoremap <Up> :echo "Press w."<CR>
nnoremap <Down> :echo "Press s."<CR>
nnoremap <Left> :echo "Press a."<CR>
nnoremap <Right> :echo "Press d."<CR>

" rainbow parens!
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" python formatting
au BufRead,BufNewFile *.py,*.pyw set tabstop=4
au BufRead,BufNewFile *.py,*.pyw set softtabstop=4
au BufRead,BufNewFile *.py,*.pyw set shiftwidth=4

" markdown
au BufRead,BufNewFile *.md,*.markdown,*.txt set wrap linebreak nolist
